### ISSUE TITLE
AttributeError: 'Object3d' object has no attribute 'name'

### ISSUE THREAD

**Issue by sofiaesp** [isl-org/Open3D-ML#251]
I'm trying to train pointpillars model with kitti dataset, using:

`python /content/Open3D-ML/scripts/run_pipeline.py tf -c /content/Open3D-ML/ml3d/configs/pointpillars_kitti.yml --split train --dataset.dataset_path <path_to_dataset> --pipeline ObjectDetection --dataset.use_cache True --main_log_dir <path>`

But I get the following error, after it completes the preprocess and starts training:

```
  File "/content/Open3D-ML/scripts/run_pipeline.py", line 134, in <module>
    main()
  File "/content/Open3D-ML/scripts/run_pipeline.py", line 130, in main
    pipeline.run_train()
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/pipelines/object_detection.py", line 232, in run_train
    data = train_loader[i]['data']
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/dataloaders/tf_dataloader.py", line 135, in __getitem__
    data = self.transform(data, attr)
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/models/point_pillars.py", line 286, in transform
    data = self.augment_data(data, attr)
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/models/point_pillars.py", line 267, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])
  File "/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/tf/models/point_pillars.py", line 252, in load_gt_database
    if db_box.name in sample_dict.keys():
AttributeError: 'Object3d' object has no attribute 'name'
training:   0% 0/5000 [00:04<?, ?it/s]
```

**Comment by sanskar107** [comment]
@sofiaesp can you retry this with latest `dev` branch ?

**Comment by ma7555** [comment]
I have the same error running pointpillars on kitti (tf)

```
UnknownError: AttributeError: 'Object3d' object has no attribute 'name'
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/models/point_pillars.py", line 337, in batcher
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/models/point_pillars.py", line 337, in <listcomp>
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/dataloaders/tf_dataloader.py", line 128, in __getitem__
    data = self.transform(data, attr)

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/models/point_pillars.py", line 314, in transform
    data = self.augment_data(data, attr)

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/models/point_pillars.py", line 295, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])

  File "/content/Open3D-ML/Open3D-ML/ml3d/tf/models/point_pillars.py", line 280, in load_gt_database
    if db_box.name in sample_dict.keys():

AttributeError: 'Object3d' object has no attribute 'name'


	 [[{{node PyFunc}}]]
```
