### ISSUE TITLE
AttributeError: module 'open3d.open3d.visualization' has no attribute '__DEVICE_API__'

### ISSUE THREAD

**Issue by GimHuang** [isl-org/Open3D-ML#274]
I installed this version, but unfortunately, when I checked the installation, the error showed that.

```
C:\Users\KimHuang>python -c "import open3d.ml.tf as ml3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda\lib\site-packages\open3d\ml\__init__.py", line 29, in <module>
    if _open3d.__DEVICE_API__ == 'cuda':
AttributeError: module 'open3d.open3d.visualization' has no attribute '__DEVICE_API__'
```

My GPU information is showing below:
```
2021-05-12 11:30:35.998028: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2021-05-12 11:30:36.022208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.455GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
```

**Comment by sanskar107** [comment]
@GimHuang can you post how you installed Open3D and your system details.

**Comment by sanskar107** [comment]
This issue should be fixed not. Feel free to reopen in you face any problem.
