### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by luoxiaoliaolan** [isl-org/Open3D-ML#299]
Hi:
      I want to use the updated pointrcnn model to predict custom point cloud data. I modified the configuration file （pointrcnn_kitti.yml） according to the previous pointpillars detection method.
Besides, I updated open3d 0.13.0,  The environment is: pytorch 1.7.1 ， CUDA 11.0 ，1 GPU：GeForce RTX 2070 SUPER 
When I loaded the pointrcnn model for inference, I encountered this error：
Traceback (most recent call last):
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 75, in run_inference
    results = model(data)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/point_rcnn.py", line 126, in forward
    backbone_xyz)  # (B, M, 7)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/point_rcnn.py", line 1106, in forward
    scores_single, proposals_single, order_single)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/point_rcnn.py", line 1185, in distance_based_proposal
    keep_idx = nms(bev, cur_scores, nms_thres)
  File "/home/lixiang/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/ml/torch/python/ops.py", line 129, in nms
    nms_overlap_thresh=nms_overlap_thresh)
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

  This error seems to be a version issue，but I am not sure how to solve it. 
  Finally, I would like to know, the pointrcnn model provided can only detect one object('Car'), why can't it detect other objects?

**Comment by sanskar107** [comment]
Using the Open3D PyTorch ops with CUDA 11 may have stability issues. We recommend to compile PyTorch from source with compile flags '-Xcompiler -fno-gnu-unique' or use the PyTorch wheels at https://github.com/isl org/open3d_downloads/releases/tag/torch1.8.1

See https://github.com/isl-org/Open3D/issues/3324 and https://github.com/pytorch/pytorch/issues/52663 for mor information on this problem.

Regarding PointRCNN, we currently support only 'Car', we welcome community contributions in this area.

**Comment by twmht** [comment]
@sanskar107 

the link to https://github.com/islorg/open3d_downloads/releases/tag/torch1.8.1 is dead. any update on this?
