### ISSUE TITLE
What is the input/output format for Point Pillar network?

### ISSUE THREAD

**Issue by Primzahlteiler** [isl-org/Open3D-ML#381]
hello, 
I am trying to infer the pretrained point pillar network (tensorflow) from https://github.com/isl-org/Open3D-ML#object-detection on my own data,

but apparently it is not: point cloud in, detections out.

So I was wondering, where is the interface documented or can someone explain how to format my data to fit the model?

Thanks :)

**Comment by kylevedder** [comment]
Are you asking how to get the detection outputs for your data?

If you use the `scripts/run_pipeline.py` with `tf`, it's calling the `ml3d/tf/pipelines/object_detection.py` file, and if you are running with `--split test`, it's calling the `run_test()` function [which seems to have its save invocation commented out](https://github.com/isl-org/Open3D-ML/blob/master/ml3d/tf/pipelines/object_detection.py#L98). If you uncomment that line, that should save the output using your dataset loader's save function in whatever format it's configured to save with; for example, using KITTI it will save to the KITTI label format.

**Comment by Primzahlteiler** [comment]
Thank you for your respone, 

I want to see the Point Pillar tf model in action on my own point cloud. The Issue I have is that when I infer the Point pillars Network with pytorch, it works as described in the [example script](https://github.com/isl-org/Open3D-ML/blob/master/scripts/demo_obj_det.py) at least for kitti, ... except for the BEVBox3D import which can be removed ;)

When I try to use the tensorflow implementation, I was going through multiple errors of the kind:
This must be a dict
This can not be indexed
This has no attribute soandso
etc.

I ended up with the following method to transform my point cloud data to PointPillar input:
```python
@staticmethod
    def prepareData(pointCloud):
        """
        :param pointCloud: Vector3DVector from open3d of shape (number of points, 3)
            coordinates are relative to camera (left to right, front to back, bottom to top)
        :return: out finished input packet for call like
            detections = pipeline.run_inference(out, False)
        """
        #nnInputs = tf.random.uniform((1000,3), maxval=20, dtype=tf.float32)
        array = np.asarray(pointCloud, dtype=np.float32)
        array = array[0:1000,:]
        intensities = np.ones((array.shape[0], 1))
        array = np.concatenate((array, intensities), axis=1) # gib jedem Punkt wieder eine intensität von 1
        nnInputs = tf.constant(array) # funktioniert auch ohne angabe des dtype, also float64
        # xyz muss noch getestet werden
        return (nnInputs, [], [nnInputs.shape[0] * nnInputs.shape[1]], {}) 
```
I somewhat expect missing bboxes and calib to hurt me later on, but the error already occurs in the first phase of inference. As I understand it, those values are ignored until 
[boxes = model.inference_end(results, data)](https://github.com/isl-org/Open3D-ML/blob/master/ml3d/tf/pipelines/object_detection.py#L58)

for now the input format seems to be correct, and I can put my point cloud Tensor into pipeline.run_inference(), but I am stuck with the following error:

```
2021-09-24 11:24:38.505807: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

INFO - 2021-09-24 11:24:38,950 - object_detection - Restored from scripts/assets/pointpillars_tf_kitti_202012221652utc/ckpt-12

2021-09-24 11:24:39.392191: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at scatter_nd_op.cc:130 : Invalid argument: indices[13] = [260992] does not index into shape [214272,64]
Traceback (most recent call last):
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/scripts/demo_obj_det.py", line 96, in <module>
    result = pipeline.run_inference(data)[0]
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/open3d/_ml3d/tf/pipelines/object_detection.py", line 57, in run_inference
    results = model(data, training=False)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 143, in call
    x = self.extract_feats(inputs, training=training)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 104, in extract_feats
    training=training)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 719, in call
    tf.scatter_nd(indices, tf.ones_like(voxels), canvas_shape),
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8982, in scatter_nd
    indices, updates, shape, name=name, ctx=_ctx)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9025, in scatter_nd_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "/Users/juergen.lehmann/PycharmProjects/pcd-object-detection/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[13] = [260992] does not index into shape [214272,64] [Op:ScatterNd]
```

Not sure if this would be a new issue like "InvalidArgumentError in tf pointpillar implementation", but it sounds like I am still not done formatting my point cloud correctly.

Here is the file I've been trying to run through: [Road pc with lots of tree coverage](https://drive.google.com/file/d/13e7de1uw2b4edX_Iyoc3vFYojz06xrlL/view?usp=sharing)
the file is read using 
```python
pcd = o3d.io.read_point_cloud(path + "/" + self.files[i])
```

and then the "points" attribute is passed to the method above.

**Comment by kylevedder** [comment]
It looks like you have a shape error during scattering; that tells me you probably are trying to scatter a pointcloud with large range into a smaller pseudoimage, and that is failing. I suggest you look at the pointcloud ranges and the pseudoimage ranges. In the pytorch version I actually recently added a check to avoid incorrect indexing during scatter (#350)
