### ISSUE TITLE
AttributeError: 'Object3d' object has no attribute 'name' with pointpillars, kitti and tf

### ISSUE THREAD

**Issue by ma7555** [isl-org/Open3D-ML#408]
## Code
```
import os
import open3d.ml as _ml3d
import open3d.ml.tf as ml3d
import sys
from pathlib import Path
import pprint

cfg_file = "ml3d/configs/pointpillars_kitti.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.PointPillars(**cfg.model)
cfg.dataset['dataset_path'] = "/content/Open3D-ML/KITTI/Kitti"
dataset = ml3d.datasets.KITTI(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.ObjectDetection(model, dataset=dataset, device="gpu", **cfg.pipeline)

# cmd_line = ' '.join(sys.argv[:])
# with open('/content/Open3D-ML/scripts/README.md', 'r') as f:
#     readme = f.read()

# pipeline.cfg_tb = {
#     'readme': readme,
#     'cmd_line': cmd_line,
#     'dataset': pprint.pformat(cfg.dataset, indent=2),
#     'model': pprint.pformat(cfg.model, indent=2),
#     'pipeline': pprint.pformat(cfg.pipeline, indent=2)
# }

pipeline.run_train()
```

## Output
```
1 frames
/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/pipelines/object_detection.py in save_config(self, writer)
    316         with writer.as_default():
    317             with tf.name_scope("Description"):
--> 318                 tf.summary.text("Open3D-ML", self.cfg_tb['readme'], step=0)
    319                 tf.summary.text("Command line", self.cfg_tb['cmd_line'], step=0)
    320             with tf.name_scope("Configuration"):

AttributeError: 'ObjectDetection' object has no attribute 'cfg_tb'
```

Defining cfg_tb by uncommenting the code solves this but still the training pipeline is broken..

```
UnknownError: AttributeError: 'Object3d' object has no attribute 'name'
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 961, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 337, in batcher
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 337, in <listcomp>
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/dataloaders/tf_dataloader.py", line 128, in __getitem__
    data = self.transform(data, attr)

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 314, in transform
    data = self.augment_data(data, attr)

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 295, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])

  File "/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py", line 280, in load_gt_database
    if db_box.name in sample_dict.keys():

AttributeError: 'Object3d' object has no attribute 'name'
```

Inference is broken too, by removing pipeline.train() and adding the below

## Code
```
# download the weights.
ckpt_folder = './logs/'
os.makedirs(ckpt_folder, exist_ok=True)
ckpt_path = ckpt_folder + "ckpt-12.index"
pointpillar_url = "https://storage.googleapis.com/open3d-releases/model-zoo/pointpillars_kitti_202012221652utc.zip"
if not os.path.exists(ckpt_path):
    cmd = "wget {} -O {}".format(pointpillar_url, ckpt_path)
    os.system(cmd)

# load the parameters.
pipeline.load_ckpt(ckpt_path=ckpt_path)

test_split = dataset.get_split("test")
data = test_split.get_data(0)

# run inference on a single example.
# returns dict with 'predict_labels' and 'predict_scores'.
result = pipeline.run_inference(data)
```

## Output
```
INFO - 2021-11-01 22:08:16,449 - object_detection - Restored from ./logs/ckpt-12.index
INFO - 2021-11-01 22:08:16,450 - kitti - Found 7518 pointclouds for test
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-d562f183cd98> in <module>()
     47 # run inference on a single example.
     48 # returns dict with 'predict_labels' and 'predict_scores'.
---> 49 result = pipeline.run_inference(data)
     50 
     51 # evaluate performance on the test set; this will write logs to './logs'.

2 frames
/root/.local/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_pillars.py in call(self, inputs, training)
    140         :param training: toggle training run
    141         """
--> 142         inputs = unpack(inputs[0], inputs[-2])
    143         x = self.extract_feats(inputs, training=training)
    144         outs = self.bbox_head(x, training=training)

KeyError: 0
```

**Comment by mme93** [comment]
I have a similar error. Are there any solutions yet?

I run as Code:

> import open3d.ml as _ml3d
> import open3d.ml.tf as ml3d
> 
> 
> dataset = ml3d.datasets.KITTI(dataset_path='/home/test/kitti')
> 
> cfg = _ml3d.utils.Config.load_from_file("ml3d/configs/pointpillars_kitti.yml")
> 
> model = ml3d.models.PointPillars(**cfg.model)
> 
> pipeline = ml3d.pipelines.ObjectDetection(model=model, dataset=dataset,**cfg.pipeline)
> 
> pipeline.run_train()


The error in the console is:
```
2021-11-18 10:02:34.229162: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-11-18 10:02:34.229183: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-18 10:02:35.123907: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-11-18 10:02:35.123926: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-18 10:02:35.401333: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-18 10:02:35.401530: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-11-18 10:02:35.401542: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-18 10:02:35.401572: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (OE130HIWI11-ubuntu): /proc/driver/nvidia/version does not exist
2021-11-18 10:02:35.401785: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-18 10:02:35.402127: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO - 2021-11-18 10:02:35,550 - object_detection - Logging in file : ./logs/PointPillars_KITTI_tf/log_train_2021-11-18_10:02:35.txt
INFO - 2021-11-18 10:02:35,550 - kitti - Found 3712 pointclouds for training
INFO - 2021-11-18 10:02:35,590 - object_detection - Initializing from scratch.
INFO - 2021-11-18 10:02:35,591 - object_detection - Writing summary in train_log/00172_PointPillars_KITTI_tf.
INFO - 2021-11-18 10:02:35,591 - object_detection - Started training
INFO - 2021-11-18 10:02:35,592 - object_detection - === EPOCH 0/200 ===
training:   0%|                                                                                                                                            | 0/619 [00:00<?, ?it/s]2021-11-18 10:02:35.601661: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-11-18 10:02:35.621666: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2899885000 Hz
2021-11-18 10:02:36.376039: W tensorflow/core/framework/op_kernel.cc:1751] Unknown: AttributeError: 'Object3d' object has no attribute 'name'
Traceback (most recent call last):

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in batcher
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in <listcomp>
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/dataloaders/tf_dataloader.py", line 128, in __getitem__
    data = self.transform(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 317, in transform
    data = self.augment_data(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 298, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 283, in load_gt_database
    if db_box.name in sample_dict.keys():

AttributeError: 'Object3d' object has no attribute 'name'


training:   0%|                                                                                                                                            | 0/619 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'Object3d' object has no attribute 'name'
Traceback (most recent call last):

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in batcher
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in <listcomp>
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/dataloaders/tf_dataloader.py", line 128, in __getitem__
    data = self.transform(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 317, in transform
    data = self.augment_data(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 298, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 283, in load_gt_database
    if db_box.name in sample_dict.keys():

AttributeError: 'Object3d' object has no attribute 'name'


         [[{{node PyFunc}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 39, in <module>
    pipeline.run_train()
  File "/home/test/Open3D-ML/ml3d/tf/pipelines/object_detection.py", line 234, in run_train
    for data in process_bar:
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 747, in __next__
    return self._next_internal()
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()
  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'Object3d' object has no attribute 'name'
Traceback (most recent call last):

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/home/test/newVenvOpen3d/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in batcher
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 340, in <listcomp>
    batch = [dataset[i + bi]['data'] for bi in range(batch_size)]

  File "/home/test/Open3D-ML/ml3d/tf/dataloaders/tf_dataloader.py", line 128, in __getitem__
    data = self.transform(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 317, in transform
    data = self.augment_data(data, attr)

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 298, in augment_data
    self.load_gt_database(pickle_path, **cfg['ObjectSample'])

  File "/home/test/Open3D-ML/ml3d/tf/models/point_pillars.py", line 283, in load_gt_database
    if db_box.name in sample_dict.keys():

AttributeError: 'Object3d' object has no attribute 'name'


         [[{{node PyFunc}}]]
```


I'm using your master, source the local open3d-ml & use a virtual Enviroment with:
addict==2.4.0
pillow==8.3.0
matplotlib==3.3.4
numpy==1.19.5
pandas==1.0
pyyaml==5.4.1
scikit-learn==0.24.2
tqdm==4.61.2
plyfile==0.7.2
tensorflow==2.4.2

**Comment by sanskar107** [comment]
@ma7555 This is fixed in `dev` branch. It will be merged to `master` in the next release (within a week). Please use `dev` branch for now.
