### ISSUE TITLE
About Running a pretrained model for 3D object detection

### ISSUE THREAD

**Issue by X1aoXuZhu** [isl-org/Open3D-ML#419]
I use the code in Readme： Running a pretrained model for 3D object detection. But I meet some errors i want to know how to deal with it .
Error : 
/home/yanghan/anaconda3/envs/open3d/lib/python3.7/site-packages/numpy/core/_methods.py:163: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asanyarray(a)
Traceback (most recent call last):
  File "/home/yanghan/PycharmProjects/pythonProject/txt.py", line 32, in <module>
    pipeline.run_valid()
  File "/home/yanghan/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 191, in run_valid
    desc += " %s: %.03f" % (l, np.mean(v))
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by sanskar107** [comment]
@X1aoXuZhu Could you post your training script ? Also please try to reproduce this issue with `dev` branch.

**Comment by sanskar107** [comment]
Closing due to inactivity, feel free to reopen this issue with an example of your training script.
