### ISSUE TITLE
Can't pickle local object while training RandLANet on S3DIS

### ISSUE THREAD

**Issue by kimdn** [isl-org/Open3D-ML#478]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Can't pickle local object while training RandLANet on S3DIS. I use pytorch.

### Steps to reproduce the bug

```python
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d

model = ml3d.models.RandLANet()

dataset_path = "/Users/kimd999/research/projects/Danny/files/public_dataset/S3DIS/Stanford3dDataset_v1.2_Aligned_Version"
dataset = ml3d.datasets.S3DIS(dataset_path=dataset_path, use_cache=True)

pipeline = ml3d.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=100)

# prints training progress in the console.
pipeline.run_train()
```

### Error message

INFO - 2022-02-15 13:24:10,927 - semantic_segmentation - DEVICE : cpu
INFO - 2022-02-15 13:24:10,927 - semantic_segmentation - Logging in file : ./logs/RandLANet_S3DIS_torch/log_train_2022-02-15_13:24:10.txt
INFO - 2022-02-15 13:24:10,929 - s3dis - Found 249 pointclouds for train
INFO - 2022-02-15 13:24:10,935 - s3dis - Found 23 pointclouds for validation
INFO - 2022-02-15 13:24:10,937 - semantic_segmentation - Initializing from scratch.
INFO - 2022-02-15 13:24:10,940 - semantic_segmentation - Writing summary in train_log/00003_RandLANet_S3DIS_torch.
INFO - 2022-02-15 13:24:10,940 - semantic_segmentation - Started training
INFO - 2022-02-15 13:24:10,940 - semantic_segmentation - === EPOCH 0/100 ===
training:   0%|                                                                                                                                         | 0/63 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_model_for_semantic_segmentation.py", line 19, in <module>
    pipeline.run_train()
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 394, in run_train
    for step, inputs in enumerate(tqdm(train_loader, desc='training')):
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/kimd999/bin/miniconda3/envs/open3d/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SemSegRandomSampler.get_point_sampler.<locals>._random_centered_gen'

### Open3D, Python and System information

```markdown
- Operating system: OSX 10.15.7
- Python version: Python 3.8.12
- Open3D version: open3d version:0.14.1
- System type: x84
- Is this remote workstation?: no
- How did you install Open3D?: pip install open3d
```

**Comment by bernhardpg** [comment]
@kimdn Seems that this was caused by `num_workers` in pytorch  being set to the wrong value, see this thread: https://github.com/pyg-team/pytorch_geometric/issues/366.

Try setting `num_workers=0` in your pipeline definition like so:
`pipeline = ml3d.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=100, num_workers=0)`

Does that solve your issue?

**Comment by LuZaiJiaoXiaL** [comment]
I used WSL ubuntu to train the models. Num_workers > 0 worked for RandLA-Net but KPConv, which was very strange.
But at least it proved that multiprocessing could work in this virtual environment. Do you have any ideas about the difference in the model deployments?

**Comment by whuhxb** [comment]
Hi @bernhardpg 

How to set num_workers when I use this command:

python scripts/run_pipeline.py torch -c ml3d/configs/randlanet_toronto3d.yml --dataset.dataset_path dataset/Toronto_3D  --pipeline SemanticSegmentation --dataset.use_cache True

**Comment by ted8201** [comment]
I set num_workers to 0 in run_pipline.py, the same error still happens.
![image](https://user-images.githubusercontent.com/40784619/212635692-ebefe554-27f9-491d-9d9c-5f8d316ed361.png)

**Comment by RauchLukas** [comment]
Hey, any new insights into how to fix the problem? 
I just ran into the same issue on a dockerized ubuntu20.04 with cudnn11.7.

Happy, if someone could share their latest fixes

**Comment by runra** [comment]
Same problem here.  Very keen to get this fixed if I can.
 
Thanks

**Comment by DCtcl** [comment]
Hi, I find a solution. Just add "num_workers:0 pin_memory: false" belong to "pipeline" in ".yaml " config file. Solution link [https://blog.csdn.net/weixin_40653140/article/details/130492849](url)
