### ISSUE TITLE
How to visualize and compare input data, ground truth and results in TensorBoard?

### ISSUE THREAD

**Issue by Nireil** [isl-org/Open3D-ML#480]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have got the summary files include *msgpack** , but when I run `tensorboard --logdir mypath` and chose  the colum of **OPEN3D**, an error shows as follow:
/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/filesystem.py:53: **BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,**
E0222 12:00:51.545484 139888637277952 _internal.py:225] Error on request:
Traceback (most recent call last):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 320, in run_wsgi
    execute(self.server.app)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 309, in execute
    application_iter = app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 525, in __call__
    return self._app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 566, in wrapper
    return wsgi_app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/security_validator.py", line 77, in __call__
    return self._application(environ, start_response_proxy)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 589, in wrapper
    return wsgi_app(environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 548, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/wrappers/request.py", line 206, in application
    resp = f(*args[:-2] + (request,))
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/tensorboard_plugin/plugin.py", line 799, in _serve_js
    return werkzeug.Response(infile.read(),
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16677: ordinal not in range(128)**

**Comment by Nireil** [comment]
And I have atempted to reproduce the result of exampls in [https://github.com/isl-org/Open3D-ML/blob/master/docs/tensorboard.md](url) , error above still exits

**Comment by Nireil** [comment]
I have solved this error by add  `encoding="utf-8"` in  "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/tensorboard_plugin/plugin.py" line 798 to `with open(js_file, encoding="utf-8") as infile:`.
**However, another error occured.** When I run `tensorboard --logdir mypath`,  the terminal reports that as follows.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] Resetting default logger to print to terminal.
[Open3D INFO] Window window_0 created.
[Open3D INFO] EGL headless mode enabled.
[Open3D INFO] ICE servers: {"stun:stun.l.google.com:19302", "turn:user:password@34.69.27.100:3478", "turn:user:password@34.69.27.100:3478?transport=tcp"}
[Open3D INFO] Set WEBRTC_STUN_SERVER environment variable add a customized WebRTC STUN server.
[Open3D INFO] WebRTC Jupyter handshake mode enabled.
FEngine (64 bits) created at 0x7fbd6c007210 (threading is enabled)
eglInitialize failed
**Fatal Python error: Segmentation fault**

Current thread 0x00007fbd73fff700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/async_event_loop.py", line 99 in _thread_main
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fbd94ff9700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socket.py", line 586 in readinto
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 371 in handle_one_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/http/server.py", line 418 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 343 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 724 in __init__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 364 in finish_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 654 in process_request_thread
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fbd95ffb700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socket.py", line 586 in readinto
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 371 in handle_one_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/http/server.py", line 420 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 343 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 724 in __init__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 364 in finish_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 654 in process_request_thread
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fbd967fc700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 295 in wait
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 330 in wait_for
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/async_event_loop.py", line 84 in run_sync
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/tensorboard_plugin/plugin.py", line 477 in _start_gui
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/open3d/visualization/tensorboard_plugin/plugin.py", line 708 in _new_window
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/wrappers/request.py", line 206 in application
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 548 in _route_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 589 in wrapper
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/empty_path_redirect.py", line 43 in __call__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/experiment_id.py", line 73 in __call__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/path_prefix.py", line 68 in __call__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/security_validator.py", line 77 in __call__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 566 in wrapper
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/backend/application.py", line 525 in __call__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 309 in execute
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 320 in run_wsgi
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 375 in handle_one_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/http/server.py", line 420 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 343 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 724 in __init__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 364 in finish_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 654 in process_request_thread
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fbd96ffd700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socket.py", line 586 in readinto
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 371 in handle_one_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/http/server.py", line 420 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 343 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 724 in __init__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 364 in finish_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 654 in process_request_thread
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fbd977fe700 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socket.py", line 586 in readinto
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 371 in handle_one_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/http/server.py", line 420 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 343 in handle
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 724 in __init__
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 364 in finish_request
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 654 in process_request_thread
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 864 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fc0e605b240 (most recent call first):
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/selectors.py", line 376 in select
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/socketserver.py", line 236 in serve_forever
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/werkzeug/serving.py", line 720 in serve_forever
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/program.py", line 295 in _run_serve_subcommand
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/program.py", line 276 in main
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/absl/app.py", line 258 in _run_main
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/absl/app.py", line 312 in run
  File "/home/johnny.pan/anaconda3/envs/open3d/lib/python3.6/site-packages/tensorboard/main.py", line 46 in run_main
  File "/home/johnny.pan/anaconda3/envs/open3d/bin/tensorboard", line 9 in <module>
**Segmentation fault**

And the colum of OPEN3D shows like this:
<img width="916" alt="截屏2022-02-24 下午4 09 32" src="https://user-images.githubusercontent.com/73781932/155484053-28e80ff5-a8cb-4e7a-9992-1089e0dd3013.png">

**Comment by ssheorey** [comment]
Hi @Nireil thanks for reporting this error. If you are getting a seg fault, please convert to a bug report, i.e. provide enough system / environment information for us to reproduce the error. Then, list the exact commands that you ran. Also include your GPU and OpenGL version supported.

Can you run these two Open3D GUI examples on your system? They are in the Open3D repo.

```
python examples/python/visualization/draw.py
python examples/python/visualization/draw_webrtc.py
```
