### ISSUE TITLE
No such file or directory: './Kitti/bboxes.pkl'

### ISSUE THREAD

**Issue by bilel-bj** [isl-org/Open3D-ML#484]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I was trying to train PointPillar with Kitti. 
I used the default script for downloading kitti and then I run this script:

But I get the following error:

### Steps to reproduce the bug

```python
`python scripts/run_pipeline.py torch -c ml3d/configs/pointpillars_kitti.yml --split train --dataset.dataset_path ./Kitti  --pipeline ObjectDetection --dataset.use_cache True
`
```

### Error message

`INFO - 2022-03-01 14:15:44,665 - object_detection - DEVICE : cuda
INFO - 2022-03-01 14:15:44,665 - object_detection - Logging in file : ./logs/PointPillars_KITTI_torch/log_train_2022-03-01_14:15:44.txt
INFO - 2022-03-01 14:15:44,665 - kitti - Found 3712 pointclouds for training
preprocess:   0%|                                                               | 0/3712 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 163, in <module>
    main()
  File "scripts/run_pipeline.py", line 153, in main
    pipeline.run_train()
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 278, in run_train
    'steps_per_epoch_train', None))
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/torch/dataloaders/torch_dataloader.py", line 62, in __init__
    self.cache_convert(name, data, attr)
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/utils/dataset_helper.py", line 56, in __call__
    output = self.func(*data)
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 232, in preprocess
    data = self.augmenter.augment(data, attr, seed=rng)
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/datasets/augment/augmentation.py", line 572, in augment
    self.load_gt_database(**cfg['ObjectSample'])
  File "/home/bilel/anaconda3/envs/cell_tower/lib/python3.6/site-packages/open3d/_ml3d/datasets/augment/augmentation.py", line 506, in load_gt_database
    db_boxes = pickle.load(open(pickle_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/media/bilel/Data/Datasets/Kitti/bboxes.pkl`

### Expected behavior

The training should work as expected in the documentation

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0]
(e.g. Python 3.8 / output from `import sys  print(sys.version)`)
- Open3D version: 0.14.1 (output from python: `print(open3d.__version__)`)
- System type: arm64 (x84 / arm64 / apple-silicon / jetson / rpi)
- Is this remote workstation?: no yes or no
- How did you install Open3D?: pip (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
```

**Comment by hietalajulius** [comment]
Hi @bilel-bj! Running the first script from here should help: https://github.com/isl-org/Open3D-ML#training-pointrcnn

(`python scripts/collect_bboxes.py --dataset_path <path_to_data_root>`)

**Comment by yfq512** [comment]
@hietalajulius Hi. Does the Open3D-ML project provide code for preprocessing the S3DIS dataset. I think it's necessary to perform data preprocessing before training.
