### ISSUE TITLE
Summarize the bug "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

### ISSUE THREAD

**Issue by Nikolatesla-lj** [isl-org/Open3D-ML#510]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

~/anaconda3/envs/Genv3D/bin/python ~/Downloads/Open3D-ML-master/examples/vis_pred.py
INFO - 2022-04-07 14:08:39,636 - semantic_segmentation - Loading checkpoint /home/ljian/Downloads/Open3D-ML-master/examples/vis_weights_RandLANet.pth
INFO - 2022-04-07 14:08:41,694 - semantic_segmentation - Loading checkpoint /home/ljian/Downloads/Open3D-ML-master/examples/vis_weights_KPFCNN.pth
test 0/1: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 78416/78726 [00:02<00:00, 33596.46it/s]Traceback (most recent call last):
  File "~/Downloads/Open3D-ML-master/examples/vis_pred.py", line 163, in <module>
    main()
  File "~/Downloads/Open3D-ML-master/examples/vis_pred.py", line 151, in main
    pcs_with_pred = pred_custom_data(pc_names, pcs, pipeline_r, pipeline_k)
  File "~/Downloads/Open3D-ML-master/examples/vis_pred.py", line 40, in pred_custom_data
    results_r = pipeline_r.run_inference(data)
  File "~/anaconda3/envs/Genv3D/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 172, in run_inference
    valid_scores, valid_labels = filter_valid_label(
  File "~/anaconda3/envs/Genv3D/lib/python3.8/site-packages/open3d/_ml3d/torch/modules/losses/semseg_loss.py", line 19, in filter_valid_label
    valid_scores = torch.gather(valid_scores, 0,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Steps to reproduce the bug

```python
1.run the vis_pred.py 
2.terminals prompts RuntimeError:Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Open3D, Python and System information

```markdown
- Operating system: (Ubuntu 20.04)
- Python version: (e.g. Python 3.8)
- Open3D version: (open3d_ML 0.15.1)
- Is this remote workstation?: no
- How did you install Open3D?: (conda)
```

**Comment by conby** [comment]
Same here,

Open3D, Python and System information
- Operating system: (Ubuntu 18.04, Nvidia Jetson/aarch64)
- Python version: (e.g. Python 3.6)
- Open3D version: (open3d_ML 0.15.1)
- Is this remote workstation?: no
- How did you install Open3D?: (build from source)

**Comment by lovelyyoshino** [comment]
I can see the bug in 
```
        metric = SemSegMetric()
        valid_scores, valid_labels = filter_valid_label(
            torch.tensor(inference_result['predict_scores']).to(device),
            torch.tensor(data['label']), model.cfg.num_classes,
            model.cfg.ignored_label_inds, device)
        metric.update(valid_scores, valid_labels)
        log.info(f"Accuracy : {metric.acc()}")
        log.info(f"IoU : {metric.iou()}")
```
 which can see in https://github.com/isl-org/Open3D-ML/issues/435

**Comment by RuiMargarido** [comment]
We have had this error while training PointTransformer on a CustomDataset. We managed to fix this, by changing run_inference in semantic_segmentation.py. 

We changed line 161, to replicate what is going on in run_test(), ie:
Add
```python
if hasattr(inputs['data'], 'to'):
    inputs['data'].to(device)
```
before
```python
results = model(inputs['data'])
```

**Comment by anuzk13** [comment]
Thank you @RuiMargarido this worked for me!
