### ISSUE TITLE
'ml_ops' not defined when doing inference with point transformers

### ISSUE THREAD

**Issue by biophase** [isl-org/Open3D-ML#513]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Running inference with point transformers returns the following error after calling `pipeline.run_inference(data)`: 

**Error message**
`Exception has occurred: NameError
name 'ml_ops' is not defined`

Searching through the source it is not clear to me where ml_ops is being used. My assumption is it's an alias to `open3d.ml.tf.ops` but the name `ml_ops` does not come up when performing a search. I'm running Ubuntu 20.04

The error is also produced when executing the predefined script:
```
python scripts/run_pipeline.py tf -c ml3d/configs/pointtransformer_s3dis.yml --split test --dataset.dataset_path../Datasets/S3DIS --pipeline SemanticSegmentation --dataset.use_cache True
```
edit: 
Does anyone have the same issue or a suggestion for a solution? 
Thanks in advance.

**Comment by sanskar107** [comment]
Could you share more details about the error message ? (e.g. the line number, file etc..)

**Comment by biophase** [comment]
@sanskar107 Thank you for looking into this. Here is the complete output after running `scripts/run_pipeline.py`


```
python scripts/run_pipeline.py tf -c ml3d/configs/pointtransformer_s3dis.yml --split test --dataset.dataset_path ../Datasets/S3DIS --pipeline SemanticSegmentation --dataset.use_cache True
regular arguments
batch_size: null
cfg_dataset: null
cfg_file: ml3d/configs/pointtransformer_s3dis.yml
cfg_model: null
cfg_pipeline: null
ckpt_path: null
dataset: null
dataset_path: null
device: gpu
framework: tf
main_log_dir: null
max_epochs: null
mode: null
model: null
pipeline: SemanticSegmentation
seed: 0
split: test

extra arguments
dataset.dataset_path: ../Datasets/S3DIS
dataset.use_cache: 'True'

WARNING - 2022-04-14 14:26:03,568 - deprecation - From /home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
INFO - 2022-04-14 14:26:07,640 - semantic_segmentation - Initializing from scratch.
INFO - 2022-04-14 14:26:07,640 - semantic_segmentation - Logging in file : /home/hristo/Desktop/PCD_Tests/log_test_2022-04-14_14:26:07.txt
INFO - 2022-04-14 14:26:07,641 - semantic_segmentation - Started testing
INFO - 2022-04-14 14:26:07,641 - s3dis - Found 68 pointclouds for test
test:   0%|                                                                          | 0/68 [00:00<?, ?it/s]INFO - 2022-04-14 14:26:08,926 - semantic_segmentation - running inference
test:   0%|                                                                          | 0/68 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 163, in <module>
    main()
  File "scripts/run_pipeline.py", line 151, in main
    pipeline.run_test()
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/open3d/_ml3d/tf/pipelines/semantic_segmentation.py", line 169, in run_test
    results = self.run_inference(data)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/open3d/_ml3d/tf/pipelines/semantic_segmentation.py", line 132, in run_inference
    results = model(inputs, training=False)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_transformer.py", line 205, in call
    training=training)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 421, in call
    inputs, training=training, mask=mask)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 556, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1030, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/open3d/_ml3d/tf/models/point_transformer.py", line 585, in call
    tf.int64)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 710, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 597, in py_func_common
    result = func(*[np.array(x) for x in inp])
  File "/home/hristo/anaconda3/envs/open3dml/lib/python3.7/site-packages/open3d/_ml3d/tf/utils/pointnet/pointnet2_utils.py", line 47, in furthest_point_sample_v2
    out = ml_ops.furthest_point_sampling(
NameError: name 'ml_ops' is not defined
```

Some additional info:

- I'm running Tensorflow 2.5.3 (from requirements-tensorflow.txt)
- The issue is unique to PointTransformer (tf), all other networks do not raise this error

**Comment by biophase** [comment]
@sanskar107 Thanks, that was the fix indeed. I opened a PR here #520
