### ISSUE TITLE
AttributeError in trainning RandLANet using SemSegSpatiallyRegularSampler

### ISSUE THREAD

**Issue by Nireil** [isl-org/Open3D-ML#529]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have been trying to train RandLANet on Toronto3D using torch pipeline, and I select the SemSegSpatiallyRegularSampler as the  dataset's sampler which is defaultly SemSegRandomSampler. But I get a AttributeError: 'SemSegSpatiallyRegularSampler' object has no attribute 'cloud_id'. It seems that **get_point_sampler couldn't get self.cloud_id from get_cloud_sampler when split='train'** .

### Steps to reproduce the bug

```python
cd scripts/train_scripts
sh randlanet_toronto.sh torch #path-to-Toronto3D
( I used the config of randlanet_toronto3d as follows.)
dataset:
  name: Toronto3D
  cache_dir: ./logs/cache
  dataset_path: # path/to/your/dataset
  class_weights: [41697357, 1745448, 6572572, 19136493, 674897, 897825, 4634634, 374721]
  ignored_label_inds:
  - 0
  num_classes: 8
  num_points: 65536
  test_files:
  - L002.ply
  test_result_folder: ./test
  train_files:
  - L001.ply
  - L003.ply
  val_files:
  - L004.ply
  use_cache: true
  sampler:
    name: SemSegSpatiallyRegularSampler
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 8
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.05
  augment:
    recenter:
      dim: [0, 1, 2]
    normalize:
      points:
        method: linear
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
```

### Error message

Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 163, in <module>
    main()
  File "scripts/run_pipeline.py", line 153, in main
    pipeline.run_train()
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 407, in run_train
    for step, inputs in enumerate(tqdm(train_loader, desc='training')):
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/open3d/_ml3d/torch/dataloaders/torch_dataloader.py", line 87, in __getitem__
    data = self.transform(data, attr)
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/open3d/_ml3d/torch/models/randlanet.py", line 175, in transform
    pc, selected_idxs, center_point = self.trans_point_sampler(
  File "/data/panjieyun/.conda/envs/open3d/lib/python3.8/site-packages/open3d/_ml3d/datasets/samplers/semseg_spatially_regular.py", line 79, in _random_centered_gen
    cloud_id = self.cloud_id
AttributeError: 'SemSegSpatiallyRegularSampler' object has no attribute 'cloud_id'

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8.13
- Open3D version: 0.15.2
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
```

**Comment by whuhxb** [comment]
Hi @Nireil 

Have you ever solved this bug? Thanks.

**Comment by Nireil** [comment]
> Hi @Nireil
> 
> Have you ever solved this bug? Thanks.

Actually, I don't solved this bug, but I have built [my RandLANet](https://github.com/Nireil/PCSegmentaion) based on this repo. It works and the bug doesn't appear, but the score is lower than RandomSampler. I think that the SemSegSpatiallyRegularSampler is only used when testing.

**Comment by whuhxb** [comment]
> > Hi @Nireil
> > Have you ever solved this bug? Thanks.
> 
> Actually, I don't solved this bug, but I have built [my RandLANet](https://github.com/Nireil/PCSegmentaion) based on this repo. It works and the bug doesn't appear, but the score is lower than RandomSampler. I think that the SemSegSpatiallyRegularSampler is only used when testing.

OK. Thanks a lot. I will try this RandLANet code. Have you ever met this bug in PyTorch version using RandomSample in training like below?

training:   0%|          | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/export/home2/hanxiaobing/Documents/Open3D-ML-code/Open3D-ML/scripts/run_pipeline.py", line 246, in <module>
    sys.exit(main())
  File "/export/home2/hanxiaobing/Documents/Open3D-ML-code/Open3D-ML/scripts/run_pipeline.py", line 180, in main
    pipeline.run_train()
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 406, in run_train
    for step, inputs in enumerate(tqdm(train_loader, desc='training')):
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1048, in __init__
    w.start()
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/export/home2/hanxiaobing/anaconda3/envs/Open3D-ML-Pytorch/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SemSegRandomSampler.get_point_sampler.<locals>._random_centered_gen'
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors

**Comment by Nireil** [comment]
Sorry, I didn't meet this bug ever.

**Comment by whuhxb** [comment]
> Sorry, I didn't meet this bug ever.

Hi @Nireil, 
I have downloaded your code, and try to run it. I have go through the code. How to obtain the processed_data from original_data? Which python code to run this? I haven't find it. 
Thanks a lot.

**Comment by whuhxb** [comment]
> > Hi @Nireil
> > Have you ever solved this bug? Thanks.
> 
> Actually, I don't solved this bug, but I have built [my RandLANet](https://github.com/Nireil/PCSegmentaion) based on this repo. It works and the bug doesn't appear, but the score is lower than RandomSampler. I think that the SemSegSpatiallyRegularSampler is only used when testing.

In the training process, it just uses the RandomSampler.

**Comment by whuhxb** [comment]
> Hi @Nireil
> 
> Have you ever solved this bug? Thanks.

Hi, 
   Which version of code you utilized when producing these bugs? 
Thanks.
