### ISSUE TITLE
Summarize the bug (e.g., "Segmentation Fault while training RandLANet on S3DIS")

### ISSUE THREAD

**Issue by lahalan** [isl-org/Open3D-ML#532]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

AttributeError: 'ConfigDict' object has no attribute 'optimizer'

### Steps to reproduce the bug

```python
#### **I got following error , the  _ml3d.utils.Config may not read the optimizer:**
`Traceback (most recent call last):
  File "/media/tcsys521/G/python/Open3D-ML-master/Semantic Segmentation.py", line 40, in <module>
    pipeline.run_train()
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 329, in run_train
    print(f"cfg.optimizer: {cfg.optimizer.lr}")
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/utils/config.py", line 244, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer'`
__________________________________________________
####  My python code is 
__________________________________________________
`import os
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d
import yaml
from open3d._ml3d.torch import RandLANet, SemanticSegmentation

cfg_file = "ml3d/configs/randlanet_s3dis.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)
# cfg=yaml.safe_load(cfg_file)
path='/media/tcsys521/G/python/Pointnet_Pointnet2_pytorch-master/data/s3dis/Stanford3dDataset_v1.2_Aligned_Version'
cfg.dataset['dataset_path'] = path

print(f'cfg: {cfg}')
print(f'cfg.dataset:{type(cfg.dataset)} {cfg.dataset}')
print(f"**cfg_pipeline:{cfg.pipeline}")
# print(f"**cfg_pipeline.optimizer:{cfg.optimizer}")
# dataset = ml3d.datasets.S3DIS(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
# use a cache for storing the results of the preprocessing (default path is './logs/cache')
dataset = ml3d.datasets.S3DIS(dataset_path=path, use_cache=True)
print(f"dataset: {dataset}")

# create the model with random initialization.
# model = ml3d.models.RandLANet(**cfg.model)
print(f"cfg.model:{cfg.model}")
model = RandLANet(**cfg.model)
cfg= cfg.pipeline

pipeline = SemanticSegmentation(cfg=cfg,model=model, dataset=dataset, max_epoch=100)
# from bunch import bunchify
# from munch import DefaultMunch
# prints training progress in the console.
# pipeline.cfg=DefaultMunch.fromDict(cfg.pipeline)
pipeline.run_train()`

__________________________________________________
####  **the yml is like this**
__________________________________________________
`dataset:
  name: S3DIS
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [3370714, 2856755, 4919229, 318158, 375640,
478001, 974733, 650464, 791496, 88727, 1284130, 229758, 2272837]
  ignored_label_inds: []
  num_points: 40960
  test_area_idx: 3
  test_result_folder: ./test
  use_cache: False
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 5
  num_points: 40960
  num_classes: 13
  ignored_label_inds: []
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.04
  augment:
    recenter:
      dim: [0, 1]
    rotate:
      method: vertical
    scale:
      min_s: 0.9
      max_s: 1.1
    noise:
      noise_std: 0.001
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 3
  scheduler_gamma: 0.99
  test_batch_size: 3
  train_sum_dir: train_log
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
`
__________________________________________________
####  **But if i read the yml by yaml it works well, so**
__________________________________________________
`import yaml

# read the yml file
file_path = "../ml3d/configs/randlanet_s3dis.yml"
with open(file_path, 'r') as stream:
	try:
		cfg = yaml.safe_load(stream)
		# print all the cfg
		print(cfg)
	except yaml.YAMLError as exc:
		print(exc)`
__________________________________________________
the output is 
__________________________________________________
`{'dataset': {'name': 'S3DIS', 'dataset_path': None, 'cache_dir': './logs/cache', 'class_weights': [3370714, 2856755, 4919229, 318158, 375640, 478001, 974733, 650464, 791496, 88727, 1284130, 229758, 2272837], 'ignored_label_inds': [], 'num_points': 40960, 'test_area_idx': 3, 'test_result_folder': './test', 'use_cache': False}, 'model': {'name': 'RandLANet', 'batcher': 'DefaultBatcher', 'ckpt_path': None, 'num_neighbors': 16, 'num_layers': 5, 'num_points': 40960, 'num_classes': 13, 'ignored_label_inds': [], 'sub_sampling_ratio': [4, 4, 4, 4, 2], 'in_channels': 6, 'dim_features': 8, 'dim_output': [16, 64, 128, 256, 512], 'grid_size': 0.04, 'augment': {'recenter': {'dim': [0, 1]}, 'rotate': {'method': 'vertical'}, 'scale': {'min_s': 0.9, 'max_s': 1.1}, 'noise': {'noise_std': 0.001}}}, 'pipeline': {'name': 'SemanticSegmentation', 'optimizer': {'lr': 0.001}, 'batch_size': 2, 'main_log_dir': './logs', 'max_epoch': 200, 'save_ckpt_freq': 3, 'scheduler_gamma': 0.99, 'test_batch_size': 3, 'train_sum_dir': 'train_log', 'val_batch_size': 2, 'summary': {'record_for': [], 'max_pts': None, 'use_reference': False, 'max_outputs': 1}}}`
```

### Error message

Traceback (most recent call last):
  File "/media/tcsys521/G/python/Open3D-ML-master/Semantic Segmentation.py", line 40, in <module>
    pipeline.run_train()
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 329, in run_train
    print(f"cfg.optimizer: {cfg.optimizer.lr}")
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/utils/config.py", line 244, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/tcsys521/anaconda3/envs/torch182/lib/python3.8/site-packages/open3d/_ml3d/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer'

### Open3D, Python and System information

```markdown
- Operating system: ubuntu 20.04
- Python version: python 3.8
- Open3D version:0.15.2
- System type: x64
- Is this remote workstation?:  no
- How did you install Open3D?:  pip,
- Compiler version (if built from source): -
```

**Comment by lahalan** [comment]
when i edit the .yml file from 
`
  main_log_dir: ./logs/RandLANet_S3DIS_torch_c3
`

to 
`
  main_log_dir: ./logs/RandLANet_S3DIS_torch_c3
  logs_dir: ./logs/RandLANet_S3DIS_torch_c3
`

it works well!!! i dont know why , but it just works!!
(tips: you may need to new the logs_dir firstly)

**Comment by jinyuan30** [comment]
Hi @lihelin666 !

I met the same problem.

Could you please let me know what did you do to make it work well?  I didn't get what you mean above comment. Do you mean just change yml file or create a new folder to save logs?

**Comment by yfq512** [comment]
@JinyuanShao I met the same problem. do you solved it?
