### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by makaay2077** [isl-org/Open3D-ML#549]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi

When I do pipeline_run_test with the trained model, I get an error. Can you help? 

test 0/1: 100%|█████████▉| 2901299/2901742 [02:29<00:01, 319.36it/s]

test 0/1: 100%|██████████| 2901742/2901742 [02:30<00:00, 385.56it/s]

test 0/1: 100%|██████████| 2901742/2901742 [02:40<00:00, 385.56it/s]INFO - 2022-06-27 21:50:11,355 - parislille3d - Saved ajaccio_2 in ./test/ParisLille3D/ajaccio_2.txt.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-17-4fdca9a94ba4>](https://localhost:8080/#) in <module>()
     28 
     29 # evaluate performance on the test set; this will write logs to './logs'.
---> 30 pipeline.run_test()

[/usr/local/lib/python3.7/dist-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py](https://localhost:8080/#) in run_test(self)
    259                             results, inputs['data'], 0, save_gt=False)
    260         log.info(
--> 261             f"Overall Testing Accuracy : {self.metric_test.acc()[-1]}, mIoU : {self.metric_test.iou()[-1]}"
    262         )
    263 

TypeError: 'NoneType' object is not subscriptable

**Comment by darld** [comment]
anyone have the same problem? 

> Traceback (most recent call last):
>   File "scripts/run_pipeline.py", line 261, in <module>
>     sys.exit(main())
>   File "scripts/run_pipeline.py", line 190, in main
>     pipeline.run_test()
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 259, in run_test
>     f"Overall Testing Accuracy : {self.metric_test.acc()[-1]}, mIoU : {self.metric_test.iou()[-1]}"
> TypeError: 'NoneType' object is not subscriptable

**Comment by JakaCikac** [comment]
Hello, 

The issue still persists. Did anyone explore further?

`TypeError                                 Traceback (most recent call last)
<ipython-input-40-4337d398ddd8> in <cell line: 1>()
----> 1 pipeline.run_test()

/usr/local/lib/python3.10/dist-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py in run_test(self)
    257                             results, inputs['data'], 0, save_gt=False)
    258         log.info(
--> 259             f"Overall Testing Accuracy : {self.metric_test.acc()[-1]}, mIoU : {self.metric_test.iou()[-1]}"
    260         )
    261 

TypeError: 'NoneType' object is not subscriptable`

**Comment by antonis-nt** [comment]
same problem
