### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'augment'

### ISSUE THREAD

**Issue by raviS123-dot** [isl-org/Open3D-ML#594]
import open3d.ml.torch as ml3d
from open3d.ml.torch.models import PointPillars
from open3d.ml.torch.pipelines import SemanticSegmentation

dataset = ml3d.datasets.KITTI(dataset_path='/home/v3/Open3D-ML-master/ml3d/datasets/dataset', use_cache=True)
model = PointPillars()
pipeline = ObjectDetection(model=model, dataset=dataset, max_epoch=100)
pipeline.run_train()

----------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/v3/Desktop/kitti/train1.py", line 8, in <module>
    model = PointPillars()
  File "/home/v3/.local/lib/python3.10/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 84, in __init__
    self.augmenter = ObjdetAugmentation(self.cfg.augment, seed=self.rng)
  File "/home/v3/.local/lib/python3.10/site-packages/open3d/_ml3d/utils/config.py", line 244, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/v3/.local/lib/python3.10/site-packages/open3d/_ml3d/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'augment'

**Comment by samuelsaqueiroz** [comment]
I have the same problem here. Do you have any updates? Did you solved it?

**Comment by ricardosanunes** [comment]
Same problem here.
Were you able to solve it @raviS123-dot ?

**Comment by willlauer** [comment]
Maybe can just pass in the keyword arg? 

```python

model = PointPillars(
    voxelize={
        'voxel_size': [0.2, 0.2, 0.2]
    },
    augment={})

```

**Comment by raviS123-dot** [comment]
thanks @willlauer
