### ISSUE TITLE
Which versions of S3dis is supported for preprocessing

### ISSUE THREAD

**Issue by gardiens** [isl-org/Open3D-ML#618]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello, I wanted to preprocess  s3dis and vizualise it, but I got an error at the 184 item, so I wanted to know if the file needed is the aligned version or not, I couldn't find the information in the issue: 
`
 pc = pd.read_csv(file, header=None,
 68%|██████████████████████████████████████████████████████████▏                           | 184/272 [09:57<04:45,  3.25s/it]
Traceback (most recent call last):
  File "OpenMLtest/preprocess.py", line 2, in <module>
    dataset = ml3d.datasets.S3DIS(dataset_path='data/s3dis/raw')
  File "/opt/conda/envs/spt/lib/python3.8/site-packages/open3d/_ml3d/datasets/s3dis.py", line 87, in __init__
    self.create_ply_files(self.cfg.dataset_path, self.label_to_names)
  File "/opt/conda/envs/spt/lib/python3.8/site-packages/open3d/_ml3d/datasets/s3dis.py", line 222, in create_ply_files
    bbox = [class_name] + get_min_bbox(pc)
  File "/opt/conda/envs/spt/lib/python3.8/site-packages/open3d/_ml3d/datasets/utils/operations.py", line 502, in get_min_bbox
    cov_points = np.cov(points, rowvar=False, bias=True)
  File "<__array_function__ internals>", line 200, in cov
  File "/opt/conda/envs/spt/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2681, in cov
    avg, w_sum = average(X, axis=1, weights=w, returned=True)
  File "<__array_function__ internals>", line 200, in average
  File "/opt/conda/envs/spt/lib/python3.8/site-packages/numpy/lib/function_base.py", line 555, in average
    if scl.shape != avg_as_array.shape:
AttributeError: 'float' object has no attribute 'shape'
`

**Comment by yfq512** [comment]
@gardiens Does the Open3D-ML project provide code for preprocessing the S3DIS dataset, and is it necessary to perform data preprocessing before training?
