### ISSUE TITLE
"Cannot use ml3d on Windows10"—Exception: Open3D was not built with PyTorch support!

### ISSUE THREAD

**Issue by TIOKOJCB** [isl-org/Open3D-ML#623]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D-ML by:
```
git clone https://github.com/isl-org/Open3D-ML.git
cd Open3D-ML
```

### Error message

```shell
Traceback (most recent call last):
  File "G:\graduate_design\open3d_code\PointCloudFunction.py", line 4, in <module>
    import open3d.ml.torch as ml3d
  File "D:\Users\hasee\anaconda3\envs\open3d_ML\lib\site-packages\open3d\ml\torch\__init__.py", line 15, in <module>
    raise Exception('Open3D was not built with PyTorch support!')
Exception: Open3D was not built with PyTorch support!
```

### Open3D, Python and System information

```markdown
- Operating system:  Windows 10 64-bit
- Python version: e.g. Python 3.9
- Open3D version: 0.17
- System type:  arm64
- Is this remote workstation?:  no
- How did you install Open3D?: conda
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
```

**Comment by ssheorey** [comment]
We are happy to accept PRs for Windows support!

In the meantime, please try the Linux version in WSL2.

**Comment by MabeTrue** [comment]
I also have the same issue when configuring the environment on Windows. Has it been resolved?

**Comment by lclsdut** [comment]
I also encountered the same problem when configuring Open3D-ML and Pytorch environments in the window system. Does it have a specific solution?

**Comment by lclsdut** [comment]
Can anyone give an answer? Please..

**Comment by jxfruit** [comment]
it looks like that the Windows still cannot be supported

**Comment by nghiadt22** [comment]
Hi @ssheorey any progress on this problem?

**Comment by Ramzes30765** [comment]
Hello! @ssheorey any progress with it?
