### ISSUE TITLE
Train RandLANet from Readme does not seem to work

### ISSUE THREAD

**Issue by nikste** [isl-org/Open3D-ML#639]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

trying the code from the readme:
```
import ml3d
from ml3d.torch import RandLANet, SemanticSegmentation

# use a cache for storing the results of the preprocessing (default path is './logs/cache')
dataset = ml3d.datasets.SemanticKITTI(dataset_path='/path/to/SemanticKITTI/', use_cache=True)

# create the model with random initialization.
model = RandLANet()

pipeline = SemanticSegmentation(model=model, dataset=dataset, max_epoch=100)

# prints training progress in the console.
pipeline.run_train()

```
(after adding the imports, would be amazing if they were also included in the example code)
results in:
```
Traceback (most recent call last):
  File "/home/nikste/workspace-startup/open3d-ml/train_semseg_pipeline.py", line 15, in <module>
    pipeline.run_train()
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/torch/pipelines/semantic_segmentation.py", line 376, in run_train
    self.optimizer, self.scheduler = model.get_optimizer(cfg)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/torch/models/randlanet.py", line 354, in get_optimizer
    **cfg_pipeline.optimizer)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/utils/config.py", line 244, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer'
```
 
Am I doing something wrong here?

### Steps to reproduce the bug

```python
see above
```

### Error message

```
Traceback (most recent call last):
  File "/home/nikste/workspace-startup/open3d-ml/train_semseg_pipeline.py", line 15, in <module>
    pipeline.run_train()
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/torch/pipelines/semantic_segmentation.py", line 376, in run_train
    self.optimizer, self.scheduler = model.get_optimizer(cfg)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/torch/models/randlanet.py", line 354, in get_optimizer
    **cfg_pipeline.optimizer)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/utils/config.py", line 244, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/nikste/workspace-startup/open3d-ml/ml3d/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer'
```

### Open3D, Python and System information

```markdown
- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: (e.g. Python 3.8 / output from `import sys  print(sys.version)`)
- Open3D version: (output from python: `print(open3d.__version__)`)
- System type: (x84 / arm64 / apple-silicon / jetson / rpi)
- Is this remote workstation?: yes or no
- How did you install Open3D?: (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)
```

**Comment by nikste** [comment]
Changing the script to the following does seem to run through:
```
from open3d import _ml3d

import ml3d
from ml3d.torch import RandLANet, SemanticSegmentation

dataset_path =  '/path/to/SemanticKITTI/'
cfg_path = "ml3d/configs/randlanet_semantickitti.yml"

cfg = _ml3d.utils.Config.load_from_file(cfg_path)
dataset = ml3d.datasets.SemanticKITTI(dataset_path=dataset_path, use_cache=True)

# create the model with random initialization.
model = RandLANet(**cfg.model)

pipeline = SemanticSegmentation(model=model, dataset=dataset,   **cfg.pipeline) #max_epoch=100,

# prints training progress in the console.
pipeline.run_train()
```
